variables:
          CI_PPOJECT_NAME : 'transportal'
deploy job:
    stage: deploy
    tags:
          - transportal
    script:
          - docker build --build-arg GIT_TOKEN=${GIT_TOKEN}
                          -t "${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}-0.1.${CI_JOB_ID}" .
          - docker stop ${CI_PROJECT_NAME} || true
          - docker rm ${CI_PROJECT_NAME} || true
          - docker run --name ${CI_PROJECT_NAME}
                  -d --restart unless-stopped
                  -p 0.0.0.0:8123:8123 ${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}-0.1.${CI_JOB_ID}
