# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-27 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transporterDatabase', '0004_auto_20210217_0318'),
    ]

    operations = [
        migrations.CreateModel(
            name='InVitroInhibitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.TextField(null=True)),
                ('ic50', models.CharField(blank=True, max_length=10, null=True)),
                ('ki', models.CharField(blank=True, max_length=10, null=True)),
                ('assayType', models.CharField(blank=True, default='', max_length=30)),
                ('affectedSubstrate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affect_sub', to='transporterDatabase.Compound')),
                ('interactingChemical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interact_chem', to='transporterDatabase.Compound')),
                ('reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transporterDatabase.Reference')),
                ('trans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporterDatabase.Transporter')),
            ],
        ),
        migrations.RemoveField(
            model_name='invitrointeraction',
            name='affectedSubstrate',
        ),
        migrations.RemoveField(
            model_name='invitrointeraction',
            name='interactingChemical',
        ),
        migrations.RemoveField(
            model_name='invitrointeraction',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='invitrointeraction',
            name='trans',
        ),
        migrations.RemoveField(
            model_name='invitrosubstrate',
            name='concentration',
        ),
        migrations.RemoveField(
            model_name='invitrosubstrate',
            name='ic50',
        ),
        migrations.AddField(
            model_name='invitrosubstrate',
            name='assayType',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.DeleteModel(
            name='inVitroInteraction',
        ),
    ]
