# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-22 23:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transporterDatabase', '0005_auto_20210227_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitroinhibitor',
            name='assayType',
        ),
        migrations.RemoveField(
            model_name='invitrosubstrate',
            name='assayType',
        ),
    ]
