# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-03 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporterDatabase', '0006_auto_20210422_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporter',
            name='humanTransporter',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transporter',
            name='symbol',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
