# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-03 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporterDatabase', '0007_auto_20210503_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transporter',
            name='humanTransporter',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
