# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-09 23:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transporterDatabase', '0008_auto_20210503_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitroinhibitor',
            name='affectedSubstrate',
        ),
        migrations.RemoveField(
            model_name='invitroinhibitor',
            name='interactingChemical',
        ),
        migrations.RemoveField(
            model_name='invitroinhibitor',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='invitroinhibitor',
            name='trans',
        ),
        migrations.RemoveField(
            model_name='invitrosubstrate',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='invitrosubstrate',
            name='substrate',
        ),
        migrations.RemoveField(
            model_name='invitrosubstrate',
            name='trans',
        ),
        migrations.DeleteModel(
            name='InVitroInhibitor',
        ),
        migrations.DeleteModel(
            name='InVitroSubstrate',
        ),
    ]
