# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-22 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporterDatabase', '0009_auto_20211109_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compound',
            name='clinicalUse',
        ),
        migrations.RemoveField(
            model_name='inhibitor',
            name='cmpndClinical',
        ),
        migrations.RemoveField(
            model_name='inhibitor',
            name='substrateClinical',
        ),
        migrations.RemoveField(
            model_name='substrate',
            name='cmpndClinical',
        ),
        migrations.AddField(
            model_name='transporter',
            name='clinicalInhibitor',
            field=models.ManyToManyField(blank=True, related_name='clin_inhib', to='transporterDatabase.Compound'),
        ),
        migrations.AddField(
            model_name='transporter',
            name='clinicalSubstrate',
            field=models.ManyToManyField(blank=True, related_name='clin_sub', to='transporterDatabase.Compound'),
        ),
        migrations.AddField(
            model_name='transporter',
            name='inVitroInhibitor',
            field=models.ManyToManyField(blank=True, related_name='inVit_inhib', to='transporterDatabase.Compound'),
        ),
        migrations.AddField(
            model_name='transporter',
            name='inVitroSubstrate',
            field=models.ManyToManyField(blank=True, related_name='inVit_sub', to='transporterDatabase.Compound'),
        ),
        migrations.AlterField(
            model_name='ddi',
            name='reference',
            field=models.ManyToManyField(blank=True, to='transporterDatabase.Reference'),
        ),
    ]
